---
title: "Prepare Count Tables for Visualisation"
output:
  github_document:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)
library(tidyverse)
library(DESeq2)
library(stringi)
library(tximport)
```

```{r}
stage_to_hpf <- function(s){
  if ( s=="Egg"){ return(0)}
  if ( grepl("hpf",s)){
    return(as.numeric(gsub("hpf","",s)))
  }
  t=as.numeric(str_match(s,"t([0-9]*)")[,2])
  if ( s %in% c("t15","t30")){
    return((t/60)+133)
  } else {
    return(t + 133)
  }
}

sample_table <- readxl::read_xlsx("raw_data/SAMPLES_developmental_transcriptome_AMIL.xlsx",range = "A2:H150") %>% 
  mutate(Mother = ifelse(grepl("R",Replicates),"B","A")) %>% # adds column with cross (Mother) info G = A and R = B
  mutate(Stage = str_match(`Sample identification`,"([t]?[0-9]+[hpf]*)")[,2]) %>% 
  mutate(Stage = ifelse(is.na(Stage),"Egg",Stage)) %>% 
  select(SampleID=`Sample #`,Replicates,RIN,Stage,Mother) %>% 
  mutate(SampleID = str_replace(SampleID," ","_")) %>% 
  rowwise() %>% 
  mutate(time=stage_to_hpf(Stage)) %>% 
  ungroup() %>% 
  dplyr::rename(Tank=Replicates) %>% 
  dplyr::rename(sample=SampleID) %>% 
  dplyr::rename(time_code=Stage) %>% 
  dplyr::mutate(time_label=time_code) %>% 
  dplyr::rename(cross=Mother) %>% 
  # the code below converts the time labels to hours post fertilisation (hpi), minutes post induction (mpi) and hours post induction (hpi) to be consistent
  mutate(time_label = stri_replace_all_regex(time_label, pattern=c("t","h$","5$","0$","Egg"),
                                                         replacement=c("","hpi","5mpi","0mpi","0hpf"),
                                                        vectorize=F)) %>% 
  select(-RIN,-Tank)
```


```{r}
if ( file.exists("cache/amil2_txi.rds")){
  txi.rsem <- read_rds("cache/amil2_txi.rds")
} else {
  ts_results_files <- list.files("raw_data/morp/out_d/rsem/","*.isoforms.results",full.names = TRUE)

  sample_names <- basename(ts_results_files) %>% str_extract("([^\\.])*")

  names(ts_results_files) <- sample_names

  txi.rsem <- tximport(ts_results_files, type = "rsem", txIn = TRUE, txOut = TRUE)

  write_rds(txi.rsem,"cache/amil2_txi.rds")
}

if ( file.exists("cache/amil2_counts.tsv")){
  count_matrix <- read_tsv("cache/amil2_counts.tsv") %>% 
    dplyr::rename(gene=id)
} else {
 raw_counts_all <- txi.rsem$counts %>%
   as.data.frame() %>%
   rownames_to_column("id") %>%
   filter(grepl("^a_",id)) %>% # Only host genes
   tidyr::extract(id,into = "id",regex = "cds_(.*)_[0-9]+$")
 
 raw_counts_all %>% write_tsv("cache/amil2_counts.tsv")
}
```



```{r}
sample_order <- colnames(txi.rsem$counts)

sample_table <- sample_table[match(sample_order,sample_table$sample),]

dds <- DESeqDataSetFromTximport(txi.rsem,sample_table,design = ~ time_label)

# This performs sample normalisation and shrinks variance for low count values

vst_counts <- vst(dds,blind=FALSE) %>% 
  assay() %>% 
  as.data.frame() %>% 
  rownames_to_column("id") %>% 
  filter(grepl("^a_",id)) %>% 
  tidyr::extract(id,into = "gene",regex = "cds_(.*)_[0-9]+$")
```


```{r}
annotations <- read_tsv("raw_data/amil2_annotations.tsv") %>% 
  dplyr::select(gene=id,uniprot_id=Swissprot_acc,genename=`Gene Names`,go=`Gene Ontology IDs`,protein=`Protein names`,go_ipr=`ipr_go`,pfam_acc=Pfam_acc)


# Some annotation columns are actually lists. Parse these out and give each their own row.
uniprot_goterms <- annotations %>% 
  select(gene,go) %>% 
  separate_rows(go,sep = ";") %>% 
  mutate(go=str_trim(go)) %>% 
  na.omit() 

ipr_goterms <- annotations %>% 
  select(gene,go_ipr) %>% 
  separate_rows(go_ipr,sep = ";") %>% 
  mutate(go_ipr=str_trim(go_ipr)) %>% 
  na.omit() 

pfam_accessions <- annotations %>% 
  select(gene,pfam_acc) %>% 
  separate_rows(pfam_acc,sep = ";") %>% 
  mutate(pfam_acc = str_trim(pfam_acc)) %>% 
  na.omit()

```



```{r, eval=FALSE}
library(dbplyr)
con <- DBI::dbConnect(RSQLite::SQLite(), "shiny_data/amil2.sqlite")  
copy_to(con, as_tibble(vst_counts),name="vst_counts",overwrite = TRUE, temporary=FALSE, indexes=list("gene"))
copy_to(con, as_tibble(count_matrix),name="raw_counts",overwrite = TRUE, temporary=FALSE, indexes=list("gene"))
copy_to(con, annotations,name="annotations",overwrite = TRUE, temporary=FALSE,indexes=list("gene"))
copy_to(con, uniprot_goterms,name="uniprot_goterms",overwrite = TRUE, temporary=FALSE,indexes=list("gene"))
copy_to(con, ipr_goterms,name="ipr_goterms",overwrite = TRUE, temporary=FALSE,indexes=list("gene"))
copy_to(con, pfam_accessions, name="pfam_accessions", overwrite = TRUE, temporary = FALSE, indexes = list("gene"))
copy_to(con, sample_table, name="samples", overwrite = TRUE, temporary=FALSE)
DBI::dbDisconnect(con)
```
